package com.mioshek.chartplanner.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFC00100)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD4)
val md_theme_light_onPrimaryContainer = Color(0xFF410000)
val md_theme_light_secondary = Color(0xFF0061A6)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C37)
val md_theme_light_tertiary = Color(0xFF006D44)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF87F9BA)
val md_theme_light_onTertiaryContainer = Color(0xFF002111)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857370)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFFFFB4A8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFC00100)
val md_theme_light_outlineVariant = Color(0xFFD8C2BE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xffc00100)
val md_theme_dark_onPrimary = Color(0xffe5e5e5)
val md_theme_dark_primaryContainer = Color(0xffe3605e)
val md_theme_dark_onPrimaryContainer = Color(0xffffffff)
val md_theme_dark_secondary = Color(0xFFA0C9FF)
val md_theme_dark_onSecondary = Color(0xFF00325A)
val md_theme_dark_secondaryContainer = Color(0xFF00497F)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_tertiary = Color(0xFF6ADCA0)
val md_theme_dark_onTertiary = Color(0xFF003921)
val md_theme_dark_tertiaryContainer = Color(0xFF005232)
val md_theme_dark_onTertiaryContainer = Color(0xFF87F9BA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xff3b3b3b)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xff2c2c2c)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFFC00100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A8)
val md_theme_dark_outlineVariant = Color(0xFF534341)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFE80000)
