package com.mioshek.chartplanner.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6000A1)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF8E26DF)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF005D21)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF008733)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF004E42)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF007665)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF95002E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFD31D4A)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF7FE)
val onBackgroundLight = Color(0xFF1F1924)
val surfaceLight = Color(0xFFFDF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE8E0E7)
val onSurfaceVariantLight = Color(0xFF49454A)
val outlineLight = Color(0xFF7B757B)
val outlineVariantLight = Color(0xFFCBC4CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFDFB7FF)

val primaryDark = Color(0xFFDFB7FF)
val onPrimaryDark = Color(0xFF4B007E)
val primaryContainerDark = Color(0xFF7200BD)
val onPrimaryContainerDark = Color(0xFFF5E3FF)
val secondaryDark = Color(0xFF69DE7A)
val onSecondaryDark = Color(0xFF003911)
val secondaryContainerDark = Color(0xFF008532)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFF7CD7C2)
val onTertiaryDark = Color(0xFF00382F)
val tertiaryContainerDark = Color(0xFF006B5B)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB2B8)
val onErrorDark = Color(0xFF67001D)
val errorContainerDark = Color(0xFFAD0037)
val onErrorContainerDark = Color(0xFFFFF8F8)
val backgroundDark = Color(0xFF17111B)
val onBackgroundDark = Color(0xFFEADFED)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF49454A)
val onSurfaceVariantDark = Color(0xFFCBC4CB)
val outlineDark = Color(0xFF958F95)
val outlineVariantDark = Color(0xFF49454A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF891DDA)





